### PR TITLE
Added debian notes to PI install.

### PR DESCRIPTION
**Pull request by Dygear**
Debian works too!

### CODE REVIEW

**Comment by robotastic** [comment]
Should the Debian instructions just be added to the Linux page? Is there anything different between an Ubuntu vs Debian install? I am not sure if folks would check this page if they are not using a Pi

**Comment by Dewey3** [comment]
Not an answer to the question, but Raspberry Pi OS is a custom Debian tailored to the Raspberry Pi (they're both Bulleye), so I'm not sure there are any differences concerning Trunk-Recorder.

**Comment by Dygear** [comment]
> Not an answer to the question, but Raspberry Pi OS is a custom Debian tailored to the Raspberry Pi (they're both Bulleye), so I'm not sure there are any differences concerning Trunk-Recorder.

Yeah, fair, but I thought that maybe the Raspberry Pi people held some packages back because of the maturity of the platform or something. I thought that maybe with the amd64 was more mainstream that it might have more up to date packages.

**Comment by Dygear** [comment]
> Should the Debian instructions just be added to the Linux page? Is there anything different between an Ubuntu vs Debian install? I am not sure if folks would check this page if they are not using a Pi

The version of GNU Radio that Debian and Raspberry Pi install are the same. Ubuntu has a newer version so I'm slightly worried that the steps would be different. As Debian is the common source for Ubuntu, Pop_OS, and Raspberry Pi OS I would at some point hope to see them merged if it doesn't cause to much trouble for the writer and reader.

**Comment by Dygear** [comment]
Added `libsndfile1-dev` to Ubuntu 22.04 installed packages to allow cmake to run to completion.

**Pull request merged**
