### PR TITLE
Workaround for P25Conventional recorder going deaf & update analog/P25Conv call start times.

### PR DESCRIPTION
**Pull request by gofaster**
Workaround for [https://github.com/robotastic/trunk-recorder/issues/318](url) resets the costas_clock  on a periodic basis (currently 200 sec) in case it has gone into an errored state.    This only applies to P25Conventional recorders with QPSK modulation if they are idle.

Add system number prefix to log lines.

Add Talkgroup number and priority to log for calls that are rejected.

### CODE REVIEW

**Comment by gofaster** [comment]
For analog and P25Conventional recorders, changes to make reported call start times more reflective of reality vs file creation time.   The updated call start time is stored in the JSON metadata file.  The original wav and JSON filenames (with the encoded time) are not renamed with the updated time in case existing scripts and downstream apps rely on them.   

TRUNK-PLAYER note:  At this time, though trunk-player appears to read the start_time from the JSON file, it still stores or displays the call start time based on the timestamp in the filename.  Some massaging in the upload script is required to rename the wav and JSON file with the updated timestamp before passing it to manage.py

**Comment by robotastic** [comment]
Nice work - I will go give this a look through and try. It makes sense to me, I will just see if there are some ways to streamline things.

**Comment by gofaster** [comment]
src_list entries from a signalling decoder (MDC1200) were not cleared when an analog_recorder restarts.  It keeps growing with each consecutive call.
Added clear function.

**Comment by gofaster** [comment]
Add change to enable decoding of Unit ID's for Conventional P25 calls.

**Comment by gofaster** [comment]
@EricTendian This PR got a bit unwieldy as I kept making  changes after the initial PR.  Will try to resolve the merge conflicts with the latest upstream master.

**Comment by EricTendian** [comment]
@gofaster just wondering if you had a chance to do that yet - I'm happy to help since I've already been running the changes on a custom build of mine.

**Comment by gofaster** [comment]
@EricTendian Sorry,  my time and attention has been needed elsewhere recently.  I had wanted to incorporate the changes into the gnuradio 3.8 branch.  If you feel like implementing the changes, I would appreciate it.

**Comment by robotastic** [comment]
Would it be possible to just reset the Costas Clock at the end and/or beginning of each call?

I just made this change to reset it at the start of each QPSK  P25 Conventional Call. Would that have the same effect?

**Comment by EricTendian** [comment]
@gofaster no problem at all! I figured you had been busy. 

I made a PR for the unit ID related changes: https://github.com/robotastic/trunk-recorder/pull/358. @robotastic I think you introduced a compile error with the costas_clock change, I fixed it for you in that PR.

Will be making another for the improved call start time after that one is merged. Will wait for the question above to be answered before doing anything with the Costas Clock.

**Comment by gofaster** [comment]
@EricTendian   Thank you!  Correcting the analog call start time made matching up (multi-agency) incident responses much less fuzzy.

@robotastic  If I recall, that won't fix it.  When the Costas Clock gets stuck in it's rotated state, the downstream P25 Frame Assembler block stalls forever looking for a valid P25 Frame Sync magic pattern; it will never produce any output to the downstream blocks.   Even if a legit p25 call is subsequently received, the output symbol stream is nonsensical  until Costas Clock is reset.
As far as TR is concerned, the call is never set active or reaches the is_idle() check to stop and (re)start the recorder.
The proper fix would be in the Costas block itself.  Other places would break the modularity of the flowgraph/TR  Perhaps a separate watchdog thread?

**Pull request closed without merging**
