### PR TITLE
Changes Formatting and Adds Color

### PR DESCRIPTION
**Pull request by Dygear**
I've changed the output format for some of the console logs so that the console is slighly easier to follow with the eye. I've also added color to the Recording / Not Recording text so it jumps right out at you.

### CODE REVIEW

**Comment by robotastic** [comment]
Nice upgrade - thanks

**Comment by patrickfish** [comment]
Looks like this adds some blank characters before the actual talkgroup tag, example:
image

@Dygear any thoughts?

**Comment by Dygear** [comment]
I wanted to make it so you could read down the information like it was a column of of data. Easier for the eye to follow.

**Comment by bctrainers** [comment]
> Looks like this adds some blank characters before the actual talkgroup tag, example:
> image
> 
> @Dygear any thoughts?

Possible for you to show a screenshot without the background text bleeding in from the other terminal? From a glance of it, it would be this particular line (and section) causing the issue that you've observed: https://github.com/robotastic/trunk-recorder/commit/dbe1745546fe8fd7f09f3347e1c065a803bf04b6#diff-fa70b60f6dffff84d1b1323b90567febR489

**Comment by patrickfish** [comment]
It's definitely the diff above:
https://github.com/robotastic/trunk-recorder/commit/dbe1745546fe8fd7f09f3347e1c065a803bf04b6#diff-fa70b60f6dffff84d1b1323b90567febR491

I don't see how it makes it any easier to read, but easily modified.

**Pull request merged**
