### PR TITLE
Adding support for SpyServer to Dockerfile

### PR DESCRIPTION
**Pull request by EricTendian**
This PR makes a few improvements to the Dockerfile by adding support for SpyServer, via a fork of gr-osmosdr. I just submitted a PR to it which got it back in sync with the upstream repo, as well as added the AirSpy serial number patch, so we no longer need to do that as part of the build process (which is why I'm removing the patch).

This should allow the Docker setup to have support for even more SDRs.

### CODE REVIEW

**Comment by EricTendian** [comment]
(need to fix CI, apparently)

**Comment by robotastic** [comment]
Ugh! This looks like some weird build bug for gr-osmosdr.

**Comment by robotastic** [comment]
ACtually - it may have nothing to do with a change you made and was a separate that was fixed. Could you make some sort of trivial change that would retrigger the build?

**Comment by EricTendian** [comment]
@robotastic this was an issue with my changes to the gr-osmosdr fork, I submitted a PR to that repo which will fix the issue, and then I'll be able to open this PR up again.

**Comment by EricTendian** [comment]
@robotastic this is finally ready for a review now that the gr-osmosdr fork has been updated. I ended up taking out the SDRPlay changes since that's technically already available in gr-osmosdr.

**Pull request merged**
