### PR TITLE
Link WIKI from README

### PR DESCRIPTION
**Pull request by dreinhold**

### CODE REVIEW

**Comment by robotastic** [comment]
Good call - I will follow suit with the ARM & docker  install

**Comment by dreinhold** [comment]
Are you running trunk-recordor on a PI?

**Comment by robotastic** [comment]
Not for the DC system, I am using a beefy I7. I played around with a RasPi2
and it could handle a control channel and one recording channel. I think
the Pi3 could be mildly useful for a very small system.

**Comment by dreinhold** [comment]
Ha. Okay, I was trying to figure out how you could manage that.
Yeah I have an i5 chugging away for mine.

**Pull request merged**
