### PR TITLE
Change the format of filename

### PR DESCRIPTION
**Pull request by vishwajan17**
Change the format of the file Name

### CODE REVIEW

**Comment by robotastic** [comment]
Sorry - I am badd at my printf syntax - what does this change do?

**Comment by vishwajan17** [comment]
%f prints the frequency in floating point format. %e does in scientific notation where as %g prints the shortest of above two

**Comment by robotastic** [comment]
Cool - sounds like a good a change, thanks!

**Comment by dotsam** [comment]
If this is being changed, all of the filenames in create_filename() should probably be changed to match as well. As the very least, the included `encode_upload.sh` sample relies on the .wav and .json file having the same filename and only different extensions, so this is now broken after this change.

**Pull request merged**
