### PR TITLE
Improve Docker Build Github Action

### PR DESCRIPTION
**Pull request by robbiet480**
This will do a few things:

* On `push` event, Docker image `robotastic/trunk-recorder:edge` is **built** and **pushed** on DockerHub.
* On `pull_request` event, Docker image `robotastic/trunk-recorder:edge` is **built**.
* On `schedule` event, Docker image `robotastic/trunk-recorder:nightly` is **built** and **pushed** on DockerHub.
* On `push tags` event, Docker image `robotastic/trunk-recorder:<version>` and `robotastic/trunk-recorder:latest` is **built** and **pushed** on DockerHub.

It also uses the built in Github Actions cache functionality to speed up build times.

Continuation of #365, 692c852a313a9b2e36eff84de84a9789b2938ab9 and 2263cd224a43c8046a8d433f05a2471ed9f48c93

@robotastic You'll need to set two [new secrets](https://github.com/robotastic/trunk-recorder/settings/secrets/new) before this works:

- `DOCKER_USERNAME` to your Docker Hub username or email
- `DOCKER_PASSWORD` to your Docker Hub password

### CODE REVIEW

**Comment by robotastic** [comment]
Let's give this a whirl!

**Comment by robbiet480** [comment]
@robotastic Just confirming you set the two secrets mentioned?

**Comment by robotastic** [comment]
Yep - but I did it after the merge, so I might have to re-run it...

**Comment by robbiet480** [comment]
@robotastic Gotta redo it at https://github.com/robotastic/trunk-recorder/runs/778824134. Should have a re-run button top right.

**Comment by robotastic** [comment]
Yep - just hit go! looks like it didn’t get the login stuff in-time that first run.

**Comment by robotastic** [comment]
One more try - I had my email address instead of username for docker...

**Comment by robbiet480** [comment]
🎉 🎉 🎉 

image

Now just gotta get https://github.com/robotastic/docker-gnuradio/pull/4 and secrets set over there and then we will be a lean, mean Docker machine!!!

**Comment by robbiet480** [comment]
Gonna try to rework install section tonight to strongly push Docker over everything else unless users need to modify code.

**Comment by robbiet480** [comment]
@robotastic If you do merge that GNURadio one tonight, please kick off another build of trunk-recorder so that its docker images are gr3.8

**Comment by robbiet480** [comment]
Oh and if you wouldn't mind cutting a release 3.1.4 so that it updates the `latest` tag, that would be great!

**Pull request merged**
