### PR TITLE
Audio Player Code Cleanup

### PR DESCRIPTION
**Pull request by Dygear**
Everything works the same, it just makes it so the code is cleaner to read and is more more understandable with an general upgrade to HTML and Bootstrap.

### CODE REVIEW

**Comment by Dygear** [comment]
1. Would `wav` and `m4a` be better?
2. Whoops! That was my bad, I didn't actually want to commit that URL.

**Comment by kg6uyz** [comment]
I use MP3 with the older version of audioplayer.  I tried this new audioplayer.php but doesnt seem to work for me.  Opera/firefox cant display the page, i have to change it to a .html to get an output on the page but then the php code at the begining doesnt work.

**Comment by Dygear** [comment]
@kg6uyz You have to spawn a PHP server first by running `php -S 0.0.0.0:8080` then in your browser from the same computer goto http://127.0.0.1:8080/audioplayer.php, or from another computer on the same network, simply type in the IP address of the computer it's on in place of the `127.0.0.1` address.

**Comment by kg6uyz** [comment]
@Dygear Thanks, this is what i get now, 
[Mon Jul 16 07:57:12 2018] 192.168.15.126:52281 [500]: /audio.php - syntax error, unexpected '=' in /var/www/html/trunk/analog/audio.php on line 45


 Line 45 -     [$TGID, $TIME, $FREQ] = preg_split('/[-_]/', $Basename);

**Comment by Dygear** [comment]
You’re gonna need at least version 7.1 to run that code.

**Comment by kg6uyz** [comment]
@Dygear I fixed the issue, had to change `if (in_array($EXT, ['.m4a', '.wav']))` back to `if ($EXT != '.m4a')` and in my case i am using MP3 so i did this `if ($EXT != '.mp3')` and all is well and working.

**Comment by robotastic** [comment]
Let me know when this code is working good and I can merge it in.

**Comment by Dygear** [comment]
It’s working fine. There are perhaps two things that I should consider and I’d like your input on.

I’m probably going to make a define at the top of the page for the audio files to list. My default will be ‘wav’ as that’s what your program outputs by default.

The second thing is, should I make an In place configuration file reader. It’s super easy for PHP as JSON functions have been built into the core of the language since 5.2.0. That would allow for the direct read of the talk groups files as well. That I think would be the last thing to make this feature complete with the C++ code base you made.

**Comment by Dygear** [comment]
@robotastic I'm happy with that one. Let me know what the rest of you think of it.

**Comment by Dygear** [comment]
This one should work without any issues for everyone. Please check and advise.

**Comment by robotastic** [comment]
I am merging in - feel free to add more code if you want additional changes.

**Pull request merged**
