### PR TITLE
Conventional talkgroup number and alpha text assignments using .csv files

### PR DESCRIPTION
**Pull request by taclane**
Conventional channels are currently assigned sequential talkgroup numbers based on their order in the config. Because of the importance of those talkgroup numbers downstream, it is difficult to rearrange, add, or subtract conventional frequencies in a system without potentially breaking things or causing mixups with alpha tags

This PR proposes one solution through the use of the `talkgroupFile` csv as a lookup table for conventional channels by:
- Storing the channel frequency in the unused second field of the talkgroup csv
- Overriding any json Alpha Tags if a conventional system has a talkgroupFile set
- Searching for a matching talkgroup by channel frequency and using the assigned TG ID and alpha tags in system setup

If a talkgroup file is not listed for a conventional system, it falls back on sequential TG numbers and alpha tags.

Aside from the talkgroup class including a new field, there has been no additional impact noted on trunked systems. The block of code managing this only exists within the conventional system setup.

`config-conv-tg-csv.json`, `conv-tg.csv`, and `frs.csv` are provided in /examples to show how this might work.

### CODE REVIEW

**Comment by robotastic** [comment]
This looks pretty good! How about we create a new file format just for conventional channels though? I would rather do that then have fields in Talkgroup which are overloaded. We could also add in the Tone information in the future. #100 
Are there fields in the current Talkgroup file format that we could ditch for Conventional?

**Comment by taclane** [comment]
Ideally, a conventional system can benefit from almost all the same fields that a trunked system can, such as:
`TG#, Alpha Text, Description, Tag, Group`
Especially with something Rdio Scanner downstream, getting all those text fields to auto populate makes things easy to manage and display.

I agree that a tone field should be reserved for future use. Being able to copy something like like "026 DPL" or "107.2 PL" or "CSQ" from Radio Reference could make it pretty simple.  Having frequency or frequency/tone to look up call information should cover most cases.  

There's been a lot of discussion about conventional channels on here and the discord lately, so it's probably worth gathering some additional input to see what other scenarios may need to be covered.

**Comment by robotastic** [comment]
Just to keep things updated - I am working on branch that will have most of this functionality. Check out the `conventional` branch. It is almost ready for testing.

**Comment by robotastic** [comment]
OK! This should be added with #652 - I am going to close this PR. Thanks for the great idea!

**Pull request closed without merging**
