### PR TITLE
Finished unit logging script (fixes #181, can close #440)

### LINKED ISSUE #440: Unitscript failure
I’m getting a syntax error on Line 11 (“elif”) and I’m no Bash expert - but I think elif has to have a test parameter behind it. And I don’t think “!=“ is used in Bash either?

Also the readme seems to imply that I just put the script into the ~/trunk-recorder directory, but it couldn’t find it when I ran recorder. It worked with the fully delimited name (after I first noticed the file was executable -but that’s when the syntax errors popped up.)

Last question - what’s the operational difference between this and OnUnitChange?

### PR DESCRIPTION
**Pull request by rosecitytransit**
I'm pretty sure this works. I have not built trunk-recorder with with the capability to call this script yet, however I did test out the script by giving it the same parameters trunk-recorder should.

Finishes #181, can close #440

### CODE REVIEW

**Comment by rosecitytransit** [comment]
@robotastic This is working for me. You might want to test it, but I think it can be merged.

**Comment by robotastic** [comment]
I compiled things and it looks good - Thanks for the changes!

**Comment by rosecitytransit** [comment]
And thank you for getting to it. I went ahead and added in some other minor
changes I came up with.

My next goal is to address #153 and also add in the live Web page player
used on http://kcmscanner.ddns.net/

**Review by EllioTTDawson — COMMENTED** [review]
#557 #368

**Comment by EllioTTDawson** [comment]
gh pr checkout 441

**Pull request merged**
