### PR TITLE
modified version switch to build without .git repo directory and adde…

### PR DESCRIPTION
**Pull request by rabarar**
…d -DMANUAL_GITINFO define to manual add git tagging data on the cmake command line

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
This appear to fix issue #707 based on review and discussion.  I will test this in a few ways to confirm, but not for about 12 hours.  Thanks @rabarar for the effort!

**Comment by ZeroChaos-** [comment]
Lol what?  I pasted a build error.  I can't build T-R, so I can't run T-R with --version

**Comment by rabarar** [comment]
I have no such error. Did you delete your build directory and run cmake in a clean directory?

**Comment by ZeroChaos-** [comment]
I don't get the error when I build outside of the gentoo package manager, and yes I'm sure it's a clean build.  We can merge this and close my original bug and not overcomplicate this if you want.  I do suspect they may be related, but that's not a reason to hold valid fixes

**Comment by rabarar** [comment]
I wish I had gentoo so I could test it there and see why your package manager is mangling the build …

**Comment by robotastic** [comment]
Just wanted to check and see if things got resolved. Anything I can do to help?

**Comment by rabarar** [comment]
I think it’s resolved. There’s a build issue with the version of Linux that I don’t have and can’t replicate.

**Comment by ZeroChaos-** [comment]
"I" still can't build, but the PR is tested and should fix tagged build for everyone but me.  I have to invest time in this still, but I don't have it.  I would suggest merging the PR and not waiting on resolution for my issue. Keep this bug for tracking though please.

**Comment by robotastic** [comment]
Thanks for digging into this! I will go roll a new version now

**Pull request merged**
